version: '2'

services:

  kraken-ondemand-20190307:
    image: navitia/kraken:latest
    environment:
        - KRAKEN_GENERAL_instance_name=ondemand-20190307
        - KRAKEN_GENERAL_database=/srv/ed/output/ondemand-20190307.nav.lz4
        - KRAKEN_BROKER_host=rabbitmq
        - KRAKEN_GENERAL_nb_threads=2
    volumes_from:
      - tyr_beat:ro
    expose:
      - "30000"

  jormungandr:
    environment:
      - JORMUNGANDR_INSTANCE_ondemand-20190307={"key":"ondemand-20190307","zmq_socket":"tcp://kraken-ondemand-20190307:30000"}

  instances_configurator:
    environment:
      - INSTANCE_ondemand-20190307=

